%% -*- coding: utf-8 -*-
%% @private
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.11.2
-module(chat_pb).

-export([encode_msg/2, encode_msg/3]).
-export([decode_msg/2, decode_msg/3]).
-export([merge_msgs/3, merge_msgs/4]).
-export([verify_msg/2, verify_msg/3]).
-export([get_msg_defs/0]).
-export([get_msg_names/0]).
-export([get_group_names/0]).
-export([get_msg_or_group_names/0]).
-export([get_enum_names/0]).
-export([find_msg_def/1, fetch_msg_def/1]).
-export([find_enum_def/1, fetch_enum_def/1]).
-export([enum_symbol_by_value/2, enum_value_by_symbol/2]).
-export([get_service_names/0]).
-export([get_service_def/1]).
-export([get_rpc_names/1]).
-export([find_rpc_def/2, fetch_rpc_def/2]).
-export([fqbin_to_service_name/1]).
-export([service_name_to_fqbin/1]).
-export([fqbins_to_service_and_rpc_name/2]).
-export([service_and_rpc_name_to_fqbins/2]).
-export([fqbin_to_msg_name/1]).
-export([msg_name_to_fqbin/1]).
-export([fqbin_to_enum_name/1]).
-export([enum_name_to_fqbin/1]).
-export([get_package_name/0]).
-export([uses_packages/0]).
-export([source_basename/0]).
-export([get_all_source_basenames/0]).
-export([get_all_proto_names/0]).
-export([get_msg_containment/1]).
-export([get_pkg_containment/1]).
-export([get_service_containment/1]).
-export([get_rpc_containment/1]).
-export([get_enum_containment/1]).
-export([get_proto_by_msg_name_as_fqbin/1]).
-export([get_proto_by_service_name_as_fqbin/1]).
-export([get_proto_by_enum_name_as_fqbin/1]).
-export([get_protos_by_pkg_name_as_fqbin/1]).
-export([gpb_version_as_string/0, gpb_version_as_list/0]).


%% enumerated types

-export_type([]).

%% message types
-type join() ::
      #{handle                  := iodata()         % = 1
       }.

-type part() ::
      #{handle                  := iodata()         % = 1
       }.

-type chat_msg() ::
      #{text                    := iodata()         % = 1
       }.

-type state_transfer() ::
      #{msgs                    => [chat_msg()]     % = 1
       }.

-export_type(['join'/0, 'part'/0, 'chat_msg'/0, 'state_transfer'/0]).

-spec encode_msg(join() | part() | chat_msg() | state_transfer(), atom()) -> binary().
encode_msg(Msg, MsgName) when is_atom(MsgName) ->
    encode_msg(Msg, MsgName, []).

-spec encode_msg(join() | part() | chat_msg() | state_transfer(), atom(), list()) -> binary().
encode_msg(Msg, MsgName, Opts) ->
    case proplists:get_bool(verify, Opts) of
        true -> verify_msg(Msg, MsgName, Opts);
        false -> ok
    end,
    TrUserData = proplists:get_value(user_data, Opts),
    case MsgName of
        join ->
            encode_msg_join(id(Msg, TrUserData), TrUserData);
        part ->
            encode_msg_part(id(Msg, TrUserData), TrUserData);
        chat_msg ->
            encode_msg_chat_msg(id(Msg, TrUserData), TrUserData);
        state_transfer ->
            encode_msg_state_transfer(id(Msg, TrUserData),
                                      TrUserData)
    end.


encode_msg_join(Msg, TrUserData) ->
    encode_msg_join(Msg, <<>>, TrUserData).


encode_msg_join(#{handle := F1}, Bin, TrUserData) ->
    begin
        TrF1 = id(F1, TrUserData),
        e_type_string(TrF1, <<Bin/binary, 10>>, TrUserData)
    end.

encode_msg_part(Msg, TrUserData) ->
    encode_msg_part(Msg, <<>>, TrUserData).


encode_msg_part(#{handle := F1}, Bin, TrUserData) ->
    begin
        TrF1 = id(F1, TrUserData),
        e_type_string(TrF1, <<Bin/binary, 10>>, TrUserData)
    end.

encode_msg_chat_msg(Msg, TrUserData) ->
    encode_msg_chat_msg(Msg, <<>>, TrUserData).


encode_msg_chat_msg(#{text := F1}, Bin, TrUserData) ->
    begin
        TrF1 = id(F1, TrUserData),
        e_type_string(TrF1, <<Bin/binary, 10>>, TrUserData)
    end.

encode_msg_state_transfer(Msg, TrUserData) ->
    encode_msg_state_transfer(Msg, <<>>, TrUserData).


encode_msg_state_transfer(#{} = M, Bin, TrUserData) ->
    case M of
        #{msgs := F1} ->
            TrF1 = id(F1, TrUserData),
            if TrF1 == [] -> Bin;
               true ->
                   e_field_state_transfer_msgs(TrF1, Bin, TrUserData)
            end;
        _ -> Bin
    end.

e_mfield_state_transfer_msgs(Msg, Bin, TrUserData) ->
    SubBin = encode_msg_chat_msg(Msg, <<>>, TrUserData),
    Bin2 = e_varint(byte_size(SubBin), Bin),
    <<Bin2/binary, SubBin/binary>>.

e_field_state_transfer_msgs([Elem | Rest], Bin,
                            TrUserData) ->
    Bin2 = <<Bin/binary, 10>>,
    Bin3 = e_mfield_state_transfer_msgs(id(Elem,
                                           TrUserData),
                                        Bin2,
                                        TrUserData),
    e_field_state_transfer_msgs(Rest, Bin3, TrUserData);
e_field_state_transfer_msgs([], Bin, _TrUserData) ->
    Bin.

-compile({nowarn_unused_function,e_type_sint/3}).
e_type_sint(Value, Bin, _TrUserData) when Value >= 0 ->
    e_varint(Value * 2, Bin);
e_type_sint(Value, Bin, _TrUserData) ->
    e_varint(Value * -2 - 1, Bin).

-compile({nowarn_unused_function,e_type_int32/3}).
e_type_int32(Value, Bin, _TrUserData)
    when 0 =< Value, Value =< 127 ->
    <<Bin/binary, Value>>;
e_type_int32(Value, Bin, _TrUserData) ->
    <<N:64/unsigned-native>> = <<Value:64/signed-native>>,
    e_varint(N, Bin).

-compile({nowarn_unused_function,e_type_int64/3}).
e_type_int64(Value, Bin, _TrUserData)
    when 0 =< Value, Value =< 127 ->
    <<Bin/binary, Value>>;
e_type_int64(Value, Bin, _TrUserData) ->
    <<N:64/unsigned-native>> = <<Value:64/signed-native>>,
    e_varint(N, Bin).

-compile({nowarn_unused_function,e_type_bool/3}).
e_type_bool(true, Bin, _TrUserData) ->
    <<Bin/binary, 1>>;
e_type_bool(false, Bin, _TrUserData) ->
    <<Bin/binary, 0>>;
e_type_bool(1, Bin, _TrUserData) -> <<Bin/binary, 1>>;
e_type_bool(0, Bin, _TrUserData) -> <<Bin/binary, 0>>.

-compile({nowarn_unused_function,e_type_string/3}).
e_type_string(S, Bin, _TrUserData) ->
    Utf8 = unicode:characters_to_binary(S),
    Bin2 = e_varint(byte_size(Utf8), Bin),
    <<Bin2/binary, Utf8/binary>>.

-compile({nowarn_unused_function,e_type_bytes/3}).
e_type_bytes(Bytes, Bin, _TrUserData)
    when is_binary(Bytes) ->
    Bin2 = e_varint(byte_size(Bytes), Bin),
    <<Bin2/binary, Bytes/binary>>;
e_type_bytes(Bytes, Bin, _TrUserData)
    when is_list(Bytes) ->
    BytesBin = iolist_to_binary(Bytes),
    Bin2 = e_varint(byte_size(BytesBin), Bin),
    <<Bin2/binary, BytesBin/binary>>.

-compile({nowarn_unused_function,e_type_fixed32/3}).
e_type_fixed32(Value, Bin, _TrUserData) ->
    <<Bin/binary, Value:32/little>>.

-compile({nowarn_unused_function,e_type_sfixed32/3}).
e_type_sfixed32(Value, Bin, _TrUserData) ->
    <<Bin/binary, Value:32/little-signed>>.

-compile({nowarn_unused_function,e_type_fixed64/3}).
e_type_fixed64(Value, Bin, _TrUserData) ->
    <<Bin/binary, Value:64/little>>.

-compile({nowarn_unused_function,e_type_sfixed64/3}).
e_type_sfixed64(Value, Bin, _TrUserData) ->
    <<Bin/binary, Value:64/little-signed>>.

-compile({nowarn_unused_function,e_type_float/3}).
e_type_float(V, Bin, _) when is_number(V) ->
    <<Bin/binary, V:32/little-float>>;
e_type_float(infinity, Bin, _) ->
    <<Bin/binary, 0:16, 128, 127>>;
e_type_float('-infinity', Bin, _) ->
    <<Bin/binary, 0:16, 128, 255>>;
e_type_float(nan, Bin, _) ->
    <<Bin/binary, 0:16, 192, 127>>.

-compile({nowarn_unused_function,e_type_double/3}).
e_type_double(V, Bin, _) when is_number(V) ->
    <<Bin/binary, V:64/little-float>>;
e_type_double(infinity, Bin, _) ->
    <<Bin/binary, 0:48, 240, 127>>;
e_type_double('-infinity', Bin, _) ->
    <<Bin/binary, 0:48, 240, 255>>;
e_type_double(nan, Bin, _) ->
    <<Bin/binary, 0:48, 248, 127>>.

-compile({nowarn_unused_function,e_varint/3}).
e_varint(N, Bin, _TrUserData) -> e_varint(N, Bin).

-compile({nowarn_unused_function,e_varint/2}).
e_varint(N, Bin) when N =< 127 -> <<Bin/binary, N>>;
e_varint(N, Bin) ->
    Bin2 = <<Bin/binary, (N band 127 bor 128)>>,
    e_varint(N bsr 7, Bin2).


decode_msg(Bin, MsgName) when is_binary(Bin) ->
    decode_msg(Bin, MsgName, []).

decode_msg(Bin, MsgName, Opts) when is_binary(Bin) ->
    TrUserData = proplists:get_value(user_data, Opts),
    decode_msg_1_catch(Bin, MsgName, TrUserData).

-ifdef('OTP_RELEASE').
decode_msg_1_catch(Bin, MsgName, TrUserData) ->
    try decode_msg_2_doit(MsgName, Bin, TrUserData)
    catch Class:Reason:StackTrace -> error({gpb_error,{decoding_failure, {Bin, MsgName, {Class, Reason, StackTrace}}}})
    end.
-else.
decode_msg_1_catch(Bin, MsgName, TrUserData) ->
    try decode_msg_2_doit(MsgName, Bin, TrUserData)
    catch Class:Reason ->
        StackTrace = erlang:get_stacktrace(),
        error({gpb_error,{decoding_failure, {Bin, MsgName, {Class, Reason, StackTrace}}}})
    end.
-endif.

decode_msg_2_doit(join, Bin, TrUserData) ->
    id(decode_msg_join(Bin, TrUserData), TrUserData);
decode_msg_2_doit(part, Bin, TrUserData) ->
    id(decode_msg_part(Bin, TrUserData), TrUserData);
decode_msg_2_doit(chat_msg, Bin, TrUserData) ->
    id(decode_msg_chat_msg(Bin, TrUserData), TrUserData);
decode_msg_2_doit(state_transfer, Bin, TrUserData) ->
    id(decode_msg_state_transfer(Bin, TrUserData),
       TrUserData).



decode_msg_join(Bin, TrUserData) ->
    dfp_read_field_def_join(Bin,
                            0,
                            0,
                            id('$undef', TrUserData),
                            TrUserData).

dfp_read_field_def_join(<<10, Rest/binary>>, Z1, Z2,
                        F@_1, TrUserData) ->
    d_field_join_handle(Rest, Z1, Z2, F@_1, TrUserData);
dfp_read_field_def_join(<<>>, 0, 0, F@_1, _) ->
    #{handle => F@_1};
dfp_read_field_def_join(Other, Z1, Z2, F@_1,
                        TrUserData) ->
    dg_read_field_def_join(Other, Z1, Z2, F@_1, TrUserData).

dg_read_field_def_join(<<1:1, X:7, Rest/binary>>, N,
                       Acc, F@_1, TrUserData)
    when N < 32 - 7 ->
    dg_read_field_def_join(Rest,
                           N + 7,
                           X bsl N + Acc,
                           F@_1,
                           TrUserData);
dg_read_field_def_join(<<0:1, X:7, Rest/binary>>, N,
                       Acc, F@_1, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
        10 -> d_field_join_handle(Rest, 0, 0, F@_1, TrUserData);
        _ ->
            case Key band 7 of
                0 -> skip_varint_join(Rest, 0, 0, F@_1, TrUserData);
                1 -> skip_64_join(Rest, 0, 0, F@_1, TrUserData);
                2 ->
                    skip_length_delimited_join(Rest,
                                               0,
                                               0,
                                               F@_1,
                                               TrUserData);
                3 ->
                    skip_group_join(Rest, Key bsr 3, 0, F@_1, TrUserData);
                5 -> skip_32_join(Rest, 0, 0, F@_1, TrUserData)
            end
    end;
dg_read_field_def_join(<<>>, 0, 0, F@_1, _) ->
    #{handle => F@_1}.

d_field_join_handle(<<1:1, X:7, Rest/binary>>, N, Acc,
                    F@_1, TrUserData)
    when N < 57 ->
    d_field_join_handle(Rest,
                        N + 7,
                        X bsl N + Acc,
                        F@_1,
                        TrUserData);
d_field_join_handle(<<0:1, X:7, Rest/binary>>, N, Acc,
                    _, TrUserData) ->
    {NewFValue, RestF} = begin
                             Len = X bsl N + Acc,
                             <<Utf8:Len/binary, Rest2/binary>> = Rest,
                             {id(unicode:characters_to_list(Utf8, unicode),
                                 TrUserData),
                              Rest2}
                         end,
    dfp_read_field_def_join(RestF,
                            0,
                            0,
                            NewFValue,
                            TrUserData).

skip_varint_join(<<1:1, _:7, Rest/binary>>, Z1, Z2,
                 F@_1, TrUserData) ->
    skip_varint_join(Rest, Z1, Z2, F@_1, TrUserData);
skip_varint_join(<<0:1, _:7, Rest/binary>>, Z1, Z2,
                 F@_1, TrUserData) ->
    dfp_read_field_def_join(Rest, Z1, Z2, F@_1, TrUserData).

skip_length_delimited_join(<<1:1, X:7, Rest/binary>>, N,
                           Acc, F@_1, TrUserData)
    when N < 57 ->
    skip_length_delimited_join(Rest,
                               N + 7,
                               X bsl N + Acc,
                               F@_1,
                               TrUserData);
skip_length_delimited_join(<<0:1, X:7, Rest/binary>>, N,
                           Acc, F@_1, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_join(Rest2, 0, 0, F@_1, TrUserData).

skip_group_join(Bin, FNum, Z2, F@_1, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_join(Rest, 0, Z2, F@_1, TrUserData).

skip_32_join(<<_:32, Rest/binary>>, Z1, Z2, F@_1,
             TrUserData) ->
    dfp_read_field_def_join(Rest, Z1, Z2, F@_1, TrUserData).

skip_64_join(<<_:64, Rest/binary>>, Z1, Z2, F@_1,
             TrUserData) ->
    dfp_read_field_def_join(Rest, Z1, Z2, F@_1, TrUserData).

decode_msg_part(Bin, TrUserData) ->
    dfp_read_field_def_part(Bin,
                            0,
                            0,
                            id('$undef', TrUserData),
                            TrUserData).

dfp_read_field_def_part(<<10, Rest/binary>>, Z1, Z2,
                        F@_1, TrUserData) ->
    d_field_part_handle(Rest, Z1, Z2, F@_1, TrUserData);
dfp_read_field_def_part(<<>>, 0, 0, F@_1, _) ->
    #{handle => F@_1};
dfp_read_field_def_part(Other, Z1, Z2, F@_1,
                        TrUserData) ->
    dg_read_field_def_part(Other, Z1, Z2, F@_1, TrUserData).

dg_read_field_def_part(<<1:1, X:7, Rest/binary>>, N,
                       Acc, F@_1, TrUserData)
    when N < 32 - 7 ->
    dg_read_field_def_part(Rest,
                           N + 7,
                           X bsl N + Acc,
                           F@_1,
                           TrUserData);
dg_read_field_def_part(<<0:1, X:7, Rest/binary>>, N,
                       Acc, F@_1, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
        10 -> d_field_part_handle(Rest, 0, 0, F@_1, TrUserData);
        _ ->
            case Key band 7 of
                0 -> skip_varint_part(Rest, 0, 0, F@_1, TrUserData);
                1 -> skip_64_part(Rest, 0, 0, F@_1, TrUserData);
                2 ->
                    skip_length_delimited_part(Rest,
                                               0,
                                               0,
                                               F@_1,
                                               TrUserData);
                3 ->
                    skip_group_part(Rest, Key bsr 3, 0, F@_1, TrUserData);
                5 -> skip_32_part(Rest, 0, 0, F@_1, TrUserData)
            end
    end;
dg_read_field_def_part(<<>>, 0, 0, F@_1, _) ->
    #{handle => F@_1}.

d_field_part_handle(<<1:1, X:7, Rest/binary>>, N, Acc,
                    F@_1, TrUserData)
    when N < 57 ->
    d_field_part_handle(Rest,
                        N + 7,
                        X bsl N + Acc,
                        F@_1,
                        TrUserData);
d_field_part_handle(<<0:1, X:7, Rest/binary>>, N, Acc,
                    _, TrUserData) ->
    {NewFValue, RestF} = begin
                             Len = X bsl N + Acc,
                             <<Utf8:Len/binary, Rest2/binary>> = Rest,
                             {id(unicode:characters_to_list(Utf8, unicode),
                                 TrUserData),
                              Rest2}
                         end,
    dfp_read_field_def_part(RestF,
                            0,
                            0,
                            NewFValue,
                            TrUserData).

skip_varint_part(<<1:1, _:7, Rest/binary>>, Z1, Z2,
                 F@_1, TrUserData) ->
    skip_varint_part(Rest, Z1, Z2, F@_1, TrUserData);
skip_varint_part(<<0:1, _:7, Rest/binary>>, Z1, Z2,
                 F@_1, TrUserData) ->
    dfp_read_field_def_part(Rest, Z1, Z2, F@_1, TrUserData).

skip_length_delimited_part(<<1:1, X:7, Rest/binary>>, N,
                           Acc, F@_1, TrUserData)
    when N < 57 ->
    skip_length_delimited_part(Rest,
                               N + 7,
                               X bsl N + Acc,
                               F@_1,
                               TrUserData);
skip_length_delimited_part(<<0:1, X:7, Rest/binary>>, N,
                           Acc, F@_1, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_part(Rest2, 0, 0, F@_1, TrUserData).

skip_group_part(Bin, FNum, Z2, F@_1, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_part(Rest, 0, Z2, F@_1, TrUserData).

skip_32_part(<<_:32, Rest/binary>>, Z1, Z2, F@_1,
             TrUserData) ->
    dfp_read_field_def_part(Rest, Z1, Z2, F@_1, TrUserData).

skip_64_part(<<_:64, Rest/binary>>, Z1, Z2, F@_1,
             TrUserData) ->
    dfp_read_field_def_part(Rest, Z1, Z2, F@_1, TrUserData).

decode_msg_chat_msg(Bin, TrUserData) ->
    dfp_read_field_def_chat_msg(Bin,
                                0,
                                0,
                                id('$undef', TrUserData),
                                TrUserData).

dfp_read_field_def_chat_msg(<<10, Rest/binary>>, Z1, Z2,
                            F@_1, TrUserData) ->
    d_field_chat_msg_text(Rest, Z1, Z2, F@_1, TrUserData);
dfp_read_field_def_chat_msg(<<>>, 0, 0, F@_1, _) ->
    #{text => F@_1};
dfp_read_field_def_chat_msg(Other, Z1, Z2, F@_1,
                            TrUserData) ->
    dg_read_field_def_chat_msg(Other,
                               Z1,
                               Z2,
                               F@_1,
                               TrUserData).

dg_read_field_def_chat_msg(<<1:1, X:7, Rest/binary>>, N,
                           Acc, F@_1, TrUserData)
    when N < 32 - 7 ->
    dg_read_field_def_chat_msg(Rest,
                               N + 7,
                               X bsl N + Acc,
                               F@_1,
                               TrUserData);
dg_read_field_def_chat_msg(<<0:1, X:7, Rest/binary>>, N,
                           Acc, F@_1, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
        10 ->
            d_field_chat_msg_text(Rest, 0, 0, F@_1, TrUserData);
        _ ->
            case Key band 7 of
                0 -> skip_varint_chat_msg(Rest, 0, 0, F@_1, TrUserData);
                1 -> skip_64_chat_msg(Rest, 0, 0, F@_1, TrUserData);
                2 ->
                    skip_length_delimited_chat_msg(Rest,
                                                   0,
                                                   0,
                                                   F@_1,
                                                   TrUserData);
                3 ->
                    skip_group_chat_msg(Rest,
                                        Key bsr 3,
                                        0,
                                        F@_1,
                                        TrUserData);
                5 -> skip_32_chat_msg(Rest, 0, 0, F@_1, TrUserData)
            end
    end;
dg_read_field_def_chat_msg(<<>>, 0, 0, F@_1, _) ->
    #{text => F@_1}.

d_field_chat_msg_text(<<1:1, X:7, Rest/binary>>, N, Acc,
                      F@_1, TrUserData)
    when N < 57 ->
    d_field_chat_msg_text(Rest,
                          N + 7,
                          X bsl N + Acc,
                          F@_1,
                          TrUserData);
d_field_chat_msg_text(<<0:1, X:7, Rest/binary>>, N, Acc,
                      _, TrUserData) ->
    {NewFValue, RestF} = begin
                             Len = X bsl N + Acc,
                             <<Utf8:Len/binary, Rest2/binary>> = Rest,
                             {id(unicode:characters_to_list(Utf8, unicode),
                                 TrUserData),
                              Rest2}
                         end,
    dfp_read_field_def_chat_msg(RestF,
                                0,
                                0,
                                NewFValue,
                                TrUserData).

skip_varint_chat_msg(<<1:1, _:7, Rest/binary>>, Z1, Z2,
                     F@_1, TrUserData) ->
    skip_varint_chat_msg(Rest, Z1, Z2, F@_1, TrUserData);
skip_varint_chat_msg(<<0:1, _:7, Rest/binary>>, Z1, Z2,
                     F@_1, TrUserData) ->
    dfp_read_field_def_chat_msg(Rest,
                                Z1,
                                Z2,
                                F@_1,
                                TrUserData).

skip_length_delimited_chat_msg(<<1:1, X:7,
                                 Rest/binary>>,
                               N, Acc, F@_1, TrUserData)
    when N < 57 ->
    skip_length_delimited_chat_msg(Rest,
                                   N + 7,
                                   X bsl N + Acc,
                                   F@_1,
                                   TrUserData);
skip_length_delimited_chat_msg(<<0:1, X:7,
                                 Rest/binary>>,
                               N, Acc, F@_1, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_chat_msg(Rest2,
                                0,
                                0,
                                F@_1,
                                TrUserData).

skip_group_chat_msg(Bin, FNum, Z2, F@_1, TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_chat_msg(Rest,
                                0,
                                Z2,
                                F@_1,
                                TrUserData).

skip_32_chat_msg(<<_:32, Rest/binary>>, Z1, Z2, F@_1,
                 TrUserData) ->
    dfp_read_field_def_chat_msg(Rest,
                                Z1,
                                Z2,
                                F@_1,
                                TrUserData).

skip_64_chat_msg(<<_:64, Rest/binary>>, Z1, Z2, F@_1,
                 TrUserData) ->
    dfp_read_field_def_chat_msg(Rest,
                                Z1,
                                Z2,
                                F@_1,
                                TrUserData).

decode_msg_state_transfer(Bin, TrUserData) ->
    dfp_read_field_def_state_transfer(Bin,
                                      0,
                                      0,
                                      id([], TrUserData),
                                      TrUserData).

dfp_read_field_def_state_transfer(<<10, Rest/binary>>,
                                  Z1, Z2, F@_1, TrUserData) ->
    d_field_state_transfer_msgs(Rest,
                                Z1,
                                Z2,
                                F@_1,
                                TrUserData);
dfp_read_field_def_state_transfer(<<>>, 0, 0, R1,
                                  TrUserData) ->
    S1 = #{},
    if R1 == '$undef' -> S1;
       true -> S1#{msgs => lists_reverse(R1, TrUserData)}
    end;
dfp_read_field_def_state_transfer(Other, Z1, Z2, F@_1,
                                  TrUserData) ->
    dg_read_field_def_state_transfer(Other,
                                     Z1,
                                     Z2,
                                     F@_1,
                                     TrUserData).

dg_read_field_def_state_transfer(<<1:1, X:7,
                                   Rest/binary>>,
                                 N, Acc, F@_1, TrUserData)
    when N < 32 - 7 ->
    dg_read_field_def_state_transfer(Rest,
                                     N + 7,
                                     X bsl N + Acc,
                                     F@_1,
                                     TrUserData);
dg_read_field_def_state_transfer(<<0:1, X:7,
                                   Rest/binary>>,
                                 N, Acc, F@_1, TrUserData) ->
    Key = X bsl N + Acc,
    case Key of
        10 ->
            d_field_state_transfer_msgs(Rest,
                                        0,
                                        0,
                                        F@_1,
                                        TrUserData);
        _ ->
            case Key band 7 of
                0 ->
                    skip_varint_state_transfer(Rest,
                                               0,
                                               0,
                                               F@_1,
                                               TrUserData);
                1 ->
                    skip_64_state_transfer(Rest, 0, 0, F@_1, TrUserData);
                2 ->
                    skip_length_delimited_state_transfer(Rest,
                                                         0,
                                                         0,
                                                         F@_1,
                                                         TrUserData);
                3 ->
                    skip_group_state_transfer(Rest,
                                              Key bsr 3,
                                              0,
                                              F@_1,
                                              TrUserData);
                5 ->
                    skip_32_state_transfer(Rest, 0, 0, F@_1, TrUserData)
            end
    end;
dg_read_field_def_state_transfer(<<>>, 0, 0, R1,
                                 TrUserData) ->
    S1 = #{},
    if R1 == '$undef' -> S1;
       true -> S1#{msgs => lists_reverse(R1, TrUserData)}
    end.

d_field_state_transfer_msgs(<<1:1, X:7, Rest/binary>>,
                            N, Acc, F@_1, TrUserData)
    when N < 57 ->
    d_field_state_transfer_msgs(Rest,
                                N + 7,
                                X bsl N + Acc,
                                F@_1,
                                TrUserData);
d_field_state_transfer_msgs(<<0:1, X:7, Rest/binary>>,
                            N, Acc, Prev, TrUserData) ->
    {NewFValue, RestF} = begin
                             Len = X bsl N + Acc,
                             <<Bs:Len/binary, Rest2/binary>> = Rest,
                             {id(decode_msg_chat_msg(Bs, TrUserData),
                                 TrUserData),
                              Rest2}
                         end,
    dfp_read_field_def_state_transfer(RestF,
                                      0,
                                      0,
                                      cons(NewFValue, Prev, TrUserData),
                                      TrUserData).

skip_varint_state_transfer(<<1:1, _:7, Rest/binary>>,
                           Z1, Z2, F@_1, TrUserData) ->
    skip_varint_state_transfer(Rest,
                               Z1,
                               Z2,
                               F@_1,
                               TrUserData);
skip_varint_state_transfer(<<0:1, _:7, Rest/binary>>,
                           Z1, Z2, F@_1, TrUserData) ->
    dfp_read_field_def_state_transfer(Rest,
                                      Z1,
                                      Z2,
                                      F@_1,
                                      TrUserData).

skip_length_delimited_state_transfer(<<1:1, X:7,
                                       Rest/binary>>,
                                     N, Acc, F@_1, TrUserData)
    when N < 57 ->
    skip_length_delimited_state_transfer(Rest,
                                         N + 7,
                                         X bsl N + Acc,
                                         F@_1,
                                         TrUserData);
skip_length_delimited_state_transfer(<<0:1, X:7,
                                       Rest/binary>>,
                                     N, Acc, F@_1, TrUserData) ->
    Length = X bsl N + Acc,
    <<_:Length/binary, Rest2/binary>> = Rest,
    dfp_read_field_def_state_transfer(Rest2,
                                      0,
                                      0,
                                      F@_1,
                                      TrUserData).

skip_group_state_transfer(Bin, FNum, Z2, F@_1,
                          TrUserData) ->
    {_, Rest} = read_group(Bin, FNum),
    dfp_read_field_def_state_transfer(Rest,
                                      0,
                                      Z2,
                                      F@_1,
                                      TrUserData).

skip_32_state_transfer(<<_:32, Rest/binary>>, Z1, Z2,
                       F@_1, TrUserData) ->
    dfp_read_field_def_state_transfer(Rest,
                                      Z1,
                                      Z2,
                                      F@_1,
                                      TrUserData).

skip_64_state_transfer(<<_:64, Rest/binary>>, Z1, Z2,
                       F@_1, TrUserData) ->
    dfp_read_field_def_state_transfer(Rest,
                                      Z1,
                                      Z2,
                                      F@_1,
                                      TrUserData).

read_group(Bin, FieldNum) ->
    {NumBytes, EndTagLen} = read_gr_b(Bin, 0, 0, 0, 0, FieldNum),
    <<Group:NumBytes/binary, _:EndTagLen/binary, Rest/binary>> = Bin,
    {Group, Rest}.

%% Like skipping over fields, but record the total length,
%% Each field is <(FieldNum bsl 3) bor FieldType> ++ <FieldValue>
%% Record the length because varints may be non-optimally encoded.
%%
%% Groups can be nested, but assume the same FieldNum cannot be nested
%% because group field numbers are shared with the rest of the fields
%% numbers. Thus we can search just for an group-end with the same
%% field number.
%%
%% (The only time the same group field number could occur would
%% be in a nested sub message, but then it would be inside a
%% length-delimited entry, which we skip-read by length.)
read_gr_b(<<1:1, X:7, Tl/binary>>, N, Acc, NumBytes, TagLen, FieldNum)
  when N < (32-7) ->
    read_gr_b(Tl, N+7, X bsl N + Acc, NumBytes, TagLen+1, FieldNum);
read_gr_b(<<0:1, X:7, Tl/binary>>, N, Acc, NumBytes, TagLen,
          FieldNum) ->
    Key = X bsl N + Acc,
    TagLen1 = TagLen + 1,
    case {Key bsr 3, Key band 7} of
        {FieldNum, 4} -> % 4 = group_end
            {NumBytes, TagLen1};
        {_, 0} -> % 0 = varint
            read_gr_vi(Tl, 0, NumBytes + TagLen1, FieldNum);
        {_, 1} -> % 1 = bits64
            <<_:64, Tl2/binary>> = Tl,
            read_gr_b(Tl2, 0, 0, NumBytes + TagLen1 + 8, 0, FieldNum);
        {_, 2} -> % 2 = length_delimited
            read_gr_ld(Tl, 0, 0, NumBytes + TagLen1, FieldNum);
        {_, 3} -> % 3 = group_start
            read_gr_b(Tl, 0, 0, NumBytes + TagLen1, 0, FieldNum);
        {_, 4} -> % 4 = group_end
            read_gr_b(Tl, 0, 0, NumBytes + TagLen1, 0, FieldNum);
        {_, 5} -> % 5 = bits32
            <<_:32, Tl2/binary>> = Tl,
            read_gr_b(Tl2, 0, 0, NumBytes + TagLen1 + 4, 0, FieldNum)
    end.

read_gr_vi(<<1:1, _:7, Tl/binary>>, N, NumBytes, FieldNum)
  when N < (64-7) ->
    read_gr_vi(Tl, N+7, NumBytes+1, FieldNum);
read_gr_vi(<<0:1, _:7, Tl/binary>>, _, NumBytes, FieldNum) ->
    read_gr_b(Tl, 0, 0, NumBytes+1, 0, FieldNum).

read_gr_ld(<<1:1, X:7, Tl/binary>>, N, Acc, NumBytes, FieldNum)
  when N < (64-7) ->
    read_gr_ld(Tl, N+7, X bsl N + Acc, NumBytes+1, FieldNum);
read_gr_ld(<<0:1, X:7, Tl/binary>>, N, Acc, NumBytes, FieldNum) ->
    Len = X bsl N + Acc,
    NumBytes1 = NumBytes + 1,
    <<_:Len/binary, Tl2/binary>> = Tl,
    read_gr_b(Tl2, 0, 0, NumBytes1 + Len, 0, FieldNum).

merge_msgs(Prev, New, MsgName) when is_atom(MsgName) ->
    merge_msgs(Prev, New, MsgName, []).

merge_msgs(Prev, New, MsgName, Opts) ->
    TrUserData = proplists:get_value(user_data, Opts),
    case MsgName of
        join -> merge_msg_join(Prev, New, TrUserData);
        part -> merge_msg_part(Prev, New, TrUserData);
        chat_msg -> merge_msg_chat_msg(Prev, New, TrUserData);
        state_transfer ->
            merge_msg_state_transfer(Prev, New, TrUserData)
    end.

-compile({nowarn_unused_function,merge_msg_join/3}).
merge_msg_join(#{}, #{handle := NFhandle}, _) ->
    #{handle => NFhandle}.

-compile({nowarn_unused_function,merge_msg_part/3}).
merge_msg_part(#{}, #{handle := NFhandle}, _) ->
    #{handle => NFhandle}.

-compile({nowarn_unused_function,merge_msg_chat_msg/3}).
merge_msg_chat_msg(#{}, #{text := NFtext}, _) ->
    #{text => NFtext}.

-compile({nowarn_unused_function,merge_msg_state_transfer/3}).
merge_msg_state_transfer(PMsg, NMsg, TrUserData) ->
    S1 = #{},
    case {PMsg, NMsg} of
        {#{msgs := PFmsgs}, #{msgs := NFmsgs}} ->
            S1#{msgs => 'erlang_++'(PFmsgs, NFmsgs, TrUserData)};
        {_, #{msgs := NFmsgs}} -> S1#{msgs => NFmsgs};
        {#{msgs := PFmsgs}, _} -> S1#{msgs => PFmsgs};
        {_, _} -> S1
    end.


verify_msg(Msg, MsgName) when is_atom(MsgName) ->
    verify_msg(Msg, MsgName, []).

verify_msg(Msg, MsgName, Opts) ->
    TrUserData = proplists:get_value(user_data, Opts),
    case MsgName of
        join -> v_msg_join(Msg, [MsgName], TrUserData);
        part -> v_msg_part(Msg, [MsgName], TrUserData);
        chat_msg -> v_msg_chat_msg(Msg, [MsgName], TrUserData);
        state_transfer ->
            v_msg_state_transfer(Msg, [MsgName], TrUserData);
        _ -> mk_type_error(not_a_known_message, Msg, [])
    end.


-compile({nowarn_unused_function,v_msg_join/3}).
-dialyzer({nowarn_function,v_msg_join/3}).
v_msg_join(#{handle := F1} = M, Path, TrUserData) ->
    v_type_string(F1, [handle | Path], TrUserData),
    lists:foreach(fun (handle) -> ok;
                      (OtherKey) ->
                          mk_type_error({extraneous_key, OtherKey}, M, Path)
                  end,
                  maps:keys(M)),
    ok;
v_msg_join(M, Path, _TrUserData) when is_map(M) ->
    mk_type_error({missing_fields,
                   [handle] -- maps:keys(M),
                   join},
                  M,
                  Path);
v_msg_join(X, Path, _TrUserData) ->
    mk_type_error({expected_msg, join}, X, Path).

-compile({nowarn_unused_function,v_msg_part/3}).
-dialyzer({nowarn_function,v_msg_part/3}).
v_msg_part(#{handle := F1} = M, Path, TrUserData) ->
    v_type_string(F1, [handle | Path], TrUserData),
    lists:foreach(fun (handle) -> ok;
                      (OtherKey) ->
                          mk_type_error({extraneous_key, OtherKey}, M, Path)
                  end,
                  maps:keys(M)),
    ok;
v_msg_part(M, Path, _TrUserData) when is_map(M) ->
    mk_type_error({missing_fields,
                   [handle] -- maps:keys(M),
                   part},
                  M,
                  Path);
v_msg_part(X, Path, _TrUserData) ->
    mk_type_error({expected_msg, part}, X, Path).

-compile({nowarn_unused_function,v_msg_chat_msg/3}).
-dialyzer({nowarn_function,v_msg_chat_msg/3}).
v_msg_chat_msg(#{text := F1} = M, Path, TrUserData) ->
    v_type_string(F1, [text | Path], TrUserData),
    lists:foreach(fun (text) -> ok;
                      (OtherKey) ->
                          mk_type_error({extraneous_key, OtherKey}, M, Path)
                  end,
                  maps:keys(M)),
    ok;
v_msg_chat_msg(M, Path, _TrUserData) when is_map(M) ->
    mk_type_error({missing_fields,
                   [text] -- maps:keys(M),
                   chat_msg},
                  M,
                  Path);
v_msg_chat_msg(X, Path, _TrUserData) ->
    mk_type_error({expected_msg, chat_msg}, X, Path).

-compile({nowarn_unused_function,v_msg_state_transfer/3}).
-dialyzer({nowarn_function,v_msg_state_transfer/3}).
v_msg_state_transfer(#{} = M, Path, TrUserData) ->
    case M of
        #{msgs := F1} ->
            if is_list(F1) ->
                   _ = [v_msg_chat_msg(Elem, [msgs | Path], TrUserData)
                        || Elem <- F1],
                   ok;
               true ->
                   mk_type_error({invalid_list_of, {msg, chat_msg}},
                                 F1,
                                 [msgs | Path])
            end;
        _ -> ok
    end,
    lists:foreach(fun (msgs) -> ok;
                      (OtherKey) ->
                          mk_type_error({extraneous_key, OtherKey}, M, Path)
                  end,
                  maps:keys(M)),
    ok;
v_msg_state_transfer(M, Path, _TrUserData)
    when is_map(M) ->
    mk_type_error({missing_fields,
                   [] -- maps:keys(M),
                   state_transfer},
                  M,
                  Path);
v_msg_state_transfer(X, Path, _TrUserData) ->
    mk_type_error({expected_msg, state_transfer}, X, Path).

-compile({nowarn_unused_function,v_type_string/3}).
-dialyzer({nowarn_function,v_type_string/3}).
v_type_string(S, Path, _TrUserData)
    when is_list(S); is_binary(S) ->
    try unicode:characters_to_binary(S) of
        B when is_binary(B) -> ok;
        {error, _, _} ->
            mk_type_error(bad_unicode_string, S, Path)
    catch
        error:badarg ->
            mk_type_error(bad_unicode_string, S, Path)
    end;
v_type_string(X, Path, _TrUserData) ->
    mk_type_error(bad_unicode_string, X, Path).

-compile({nowarn_unused_function,mk_type_error/3}).
-spec mk_type_error(_, _, list()) -> no_return().
mk_type_error(Error, ValueSeen, Path) ->
    Path2 = prettify_path(Path),
    erlang:error({gpb_type_error,
                  {Error, [{value, ValueSeen}, {path, Path2}]}}).


-compile({nowarn_unused_function,prettify_path/1}).
-dialyzer({nowarn_function,prettify_path/1}).
prettify_path([]) -> top_level;
prettify_path(PathR) ->
    list_to_atom(lists:append(lists:join(".",
                                         lists:map(fun atom_to_list/1,
                                                   lists:reverse(PathR))))).


-compile({nowarn_unused_function,id/2}).
-compile({inline,id/2}).
id(X, _TrUserData) -> X.

-compile({nowarn_unused_function,v_ok/3}).
-compile({inline,v_ok/3}).
v_ok(_Value, _Path, _TrUserData) -> ok.

-compile({nowarn_unused_function,m_overwrite/3}).
-compile({inline,m_overwrite/3}).
m_overwrite(_Prev, New, _TrUserData) -> New.

-compile({nowarn_unused_function,cons/3}).
-compile({inline,cons/3}).
cons(Elem, Acc, _TrUserData) -> [Elem | Acc].

-compile({nowarn_unused_function,lists_reverse/2}).
-compile({inline,lists_reverse/2}).
'lists_reverse'(L, _TrUserData) -> lists:reverse(L).
-compile({nowarn_unused_function,'erlang_++'/3}).
-compile({inline,'erlang_++'/3}).
'erlang_++'(A, B, _TrUserData) -> A ++ B.


get_msg_defs() ->
    [{{msg, join},
      [#{name => handle, fnum => 1, rnum => 2, type => string,
         occurrence => required, opts => []}]},
     {{msg, part},
      [#{name => handle, fnum => 1, rnum => 2, type => string,
         occurrence => required, opts => []}]},
     {{msg, chat_msg},
      [#{name => text, fnum => 1, rnum => 2, type => string,
         occurrence => required, opts => []}]},
     {{msg, state_transfer},
      [#{name => msgs, fnum => 1, rnum => 2,
         type => {msg, chat_msg}, occurrence => repeated,
         opts => []}]}].


get_msg_names() ->
    [join, part, chat_msg, state_transfer].


get_group_names() -> [].


get_msg_or_group_names() ->
    [join, part, chat_msg, state_transfer].


get_enum_names() -> [].


fetch_msg_def(MsgName) ->
    case find_msg_def(MsgName) of
        Fs when is_list(Fs) -> Fs;
        error -> erlang:error({no_such_msg, MsgName})
    end.


-spec fetch_enum_def(_) -> no_return().
fetch_enum_def(EnumName) ->
    erlang:error({no_such_enum, EnumName}).


find_msg_def(join) ->
    [#{name => handle, fnum => 1, rnum => 2, type => string,
       occurrence => required, opts => []}];
find_msg_def(part) ->
    [#{name => handle, fnum => 1, rnum => 2, type => string,
       occurrence => required, opts => []}];
find_msg_def(chat_msg) ->
    [#{name => text, fnum => 1, rnum => 2, type => string,
       occurrence => required, opts => []}];
find_msg_def(state_transfer) ->
    [#{name => msgs, fnum => 1, rnum => 2,
       type => {msg, chat_msg}, occurrence => repeated,
       opts => []}];
find_msg_def(_) -> error.


find_enum_def(_) -> error.


-spec enum_symbol_by_value(_, _) -> no_return().
enum_symbol_by_value(E, V) ->
    erlang:error({no_enum_defs, E, V}).


-spec enum_value_by_symbol(_, _) -> no_return().
enum_value_by_symbol(E, V) ->
    erlang:error({no_enum_defs, E, V}).



get_service_names() -> [].


get_service_def(_) -> error.


get_rpc_names(_) -> error.


find_rpc_def(_, _) -> error.



-spec fetch_rpc_def(_, _) -> no_return().
fetch_rpc_def(ServiceName, RpcName) ->
    erlang:error({no_such_rpc, ServiceName, RpcName}).


%% Convert a a fully qualified (ie with package name) service name
%% as a binary to a service name as an atom.
-spec fqbin_to_service_name(_) -> no_return().
fqbin_to_service_name(X) ->
    error({gpb_error, {badservice, X}}).


%% Convert a service name as an atom to a fully qualified
%% (ie with package name) name as a binary.
-spec service_name_to_fqbin(_) -> no_return().
service_name_to_fqbin(X) ->
    error({gpb_error, {badservice, X}}).


%% Convert a a fully qualified (ie with package name) service name
%% and an rpc name, both as binaries to a service name and an rpc
%% name, as atoms.
-spec fqbins_to_service_and_rpc_name(_, _) -> no_return().
fqbins_to_service_and_rpc_name(S, R) ->
    error({gpb_error, {badservice_or_rpc, {S, R}}}).


%% Convert a service name and an rpc name, both as atoms,
%% to a fully qualified (ie with package name) service name and
%% an rpc name as binaries.
-spec service_and_rpc_name_to_fqbins(_, _) -> no_return().
service_and_rpc_name_to_fqbins(S, R) ->
    error({gpb_error, {badservice_or_rpc, {S, R}}}).


fqbin_to_msg_name(<<"chat.join">>) -> join;
fqbin_to_msg_name(<<"chat.part">>) -> part;
fqbin_to_msg_name(<<"chat.chat_msg">>) -> chat_msg;
fqbin_to_msg_name(<<"chat.state_transfer">>) -> state_transfer;
fqbin_to_msg_name(E) -> error({gpb_error, {badmsg, E}}).


msg_name_to_fqbin(join) -> <<"chat.join">>;
msg_name_to_fqbin(part) -> <<"chat.part">>;
msg_name_to_fqbin(chat_msg) -> <<"chat.chat_msg">>;
msg_name_to_fqbin(state_transfer) -> <<"chat.state_transfer">>;
msg_name_to_fqbin(E) -> error({gpb_error, {badmsg, E}}).


-spec fqbin_to_enum_name(_) -> no_return().
fqbin_to_enum_name(E) ->
    error({gpb_error, {badenum, E}}).


-spec enum_name_to_fqbin(_) -> no_return().
enum_name_to_fqbin(E) ->
    error({gpb_error, {badenum, E}}).


get_package_name() -> chat.


%% Whether or not the message names
%% are prepended with package name or not.
uses_packages() -> false.


source_basename() -> "chat.proto".


%% Retrieve all proto file names, also imported ones.
%% The order is top-down. The first element is always the main
%% source file. The files are returned with extension,
%% see get_all_proto_names/0 for a version that returns
%% the basenames sans extension
get_all_source_basenames() -> ["chat.proto"].


%% Retrieve all proto file names, also imported ones.
%% The order is top-down. The first element is always the main
%% source file. The files are returned sans .proto extension,
%% to make it easier to use them with the various get_xyz_containment
%% functions.
get_all_proto_names() -> ["chat"].


get_msg_containment("chat") ->
    [chat_msg, join, part, state_transfer];
get_msg_containment(P) ->
    error({gpb_error, {badproto, P}}).


get_pkg_containment("chat") -> undefined;
get_pkg_containment(P) ->
    error({gpb_error, {badproto, P}}).


get_service_containment("chat") -> [];
get_service_containment(P) ->
    error({gpb_error, {badproto, P}}).


get_rpc_containment("chat") -> [];
get_rpc_containment(P) ->
    error({gpb_error, {badproto, P}}).


get_enum_containment("chat") -> [];
get_enum_containment(P) ->
    error({gpb_error, {badproto, P}}).


get_proto_by_msg_name_as_fqbin(<<"chat.state_transfer">>) -> "chat";
get_proto_by_msg_name_as_fqbin(<<"chat.part">>) -> "chat";
get_proto_by_msg_name_as_fqbin(<<"chat.chat_msg">>) -> "chat";
get_proto_by_msg_name_as_fqbin(<<"chat.join">>) -> "chat";
get_proto_by_msg_name_as_fqbin(E) ->
    error({gpb_error, {badmsg, E}}).


-spec get_proto_by_service_name_as_fqbin(_) -> no_return().
get_proto_by_service_name_as_fqbin(E) ->
    error({gpb_error, {badservice, E}}).


-spec get_proto_by_enum_name_as_fqbin(_) -> no_return().
get_proto_by_enum_name_as_fqbin(E) ->
    error({gpb_error, {badenum, E}}).


-spec get_protos_by_pkg_name_as_fqbin(_) -> no_return().
get_protos_by_pkg_name_as_fqbin(E) ->
    error({gpb_error, {badpkg, E}}).



gpb_version_as_string() ->
    "4.11.2".

gpb_version_as_list() ->
    [4,11,2].
